export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';

export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const CLOSE_SESSION = 'CLOSE_SESSION';

export const HIDE_ALERT = 'HIDE_ALERT';
export const SHOW_ALERT = 'SHOW_ALERT';

export const UPLOAD_FILE= 'UPLOAD_FILE';
export const UPLOAD_SUCCESSFUL_FILE = 'UPLOAD_SUCCESSFUL_FILE';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';

export const CREATE_SUCCESSFUL_LINK = 'CREATE_SUCCESSFUL_LINK';
export const CREAR_ENLACE_ERROR = 'CREAR_ENLACE_ERROR';

export const CLEAN_STATE = 'CLEAN_STATE';

export const ADD_DOWNLOADS = 'ADD_DOWNLOADS';
export const ADD_PASSWORD = 'ADD_PASSWORD';
